version: "3"
services: 
    instanse:
        image: single
        build: 
            context: ../SingleInstance
    loadbalancer:
        container_name: scalable_loadbalance
        build: 
            context: .\nginx
        expose:
            - 80
        ports: 
            - 5000:80
        links: 
            - instanse